version: '3.8'
services:
  postgres:
    image: postgres:14
    ports:
      - '5434:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: crud-dev
    volumes:
      - db-data:/var/lib/postgresql/data
      - db-data-sql:/home/postgres_sql
volumes:
  db-data:
  db-data-sql:
